# Generated by Django 4.2.2 on 2023-07-15 23:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteos',
            fields=[
                ('id_conteos', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso_personas', models.IntegerField()),
                ('salida_personas', models.IntegerField()),
            ],
            options={
                'db_table': 'conteos',
            },
        ),
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('scale', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('locality', models.TextField(null=True)),
            ],
            options={
                'db_table': 'parks',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_reportes', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_analisis', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_grabacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_grabacion', models.TimeField()),
                ('parque', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('duracion', models.TextField()),
                ('id_conteo_personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesisapp.conteos')),
            ],
            options={
                'db_table': 'reportes',
            },
        ),
    ]
