# Generated by Django 4.2.2 on 2023-06-15 01:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteos',
            fields=[
                ('id_conteos', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso_personas', models.IntegerField()),
                ('salida_personas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_reportes', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_analisis', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora_grabacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('parque', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('duracion', models.TextField()),
                ('id_conteo_personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesisapp.conteos')),
            ],
        ),
    ]
